apiVersion: apps/v1
kind: Deployment
metadata:
  name: userauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userauth
  template:
    metadata:
      labels:
        app: userauth 
    spec:
      containers:
        - name: userauth
          image: 394549218635.dkr.ecr.us-west-2.amazonaws.com/granolahouse/userauth:2
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"  
            - name: PROD_DB_SECRET_USERAUTH_DBUSERNAME
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret-userauth
                  key: username
            - name: PROD_DB_SECRET_USERAUTH_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret-userauth
                  key: password