apiVersion: apps/v1
kind: Deployment
metadata:
  name: userauthapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userauthapi
  template:
    metadata:
      labels:
        app: userauthapi
    spec:
      containers:
        - name: userauthapi
          image: granolahouse/userauthapi:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always